workflows:
  android-aab:
    name: Urban Auto - Android AAB (Release)
    max_build_duration: 120

    environment:
      node: 22

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Android AAB (Release)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
