workflows:
  android-builds:
    name: Urban Auto - FINAL Signed Build (All APKs + AAB)
    max_build_duration: 120

    environment:
      node: 22
      java: 21
      groups:
        - supabase

    cache:
      cache_paths:
        - ~/.npm
        - node_modules
        - .next/cache
        - android/.gradle
        - ~/.gradle

    scripts:

      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Build Next.js
        script: |
          export NEXT_TELEMETRY_DISABLED=1
          npm run build

      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Generate Android icons
        script: |
          npx @capacitor/assets generate --android

      - name: Fix Gradle Wrapper (8.13)
        script: |
          cd android
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.13
          chmod +x gradlew
          cd ..

      # ---- BUILD ALL ----
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
          cd ..

      - name: Build Release APK + AAB (Signed)
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
