workflows:
  android-builds:
    name: Urban Auto - FINAL Stable Signed Build
    max_build_duration: 120

    environment:
      node: 22
      java: 21
      groups:
        - supabase

    cache:
      cache_paths:
        - ~/.npm
        - node_modules
        - .next/cache
        - android/.gradle
        - ~/.gradle

    scripts:

      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Build Next.js
        script: |
          export NEXT_TELEMETRY_DISABLED=1
          npm run build

      - name: Verify Android platform exists
        script: |
          if [ ! -d "android" ]; then
            echo "Android folder missing"
            exit 1
          fi

      - name: Sync Capacitor
        script: |
          npx cap sync android

      # ----- ALWAYS REBUILD WRAPPER CLEAN -----
      - name: Regenerate Gradle Wrapper (PERMANENT FIX)
        script: |
          cd android
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.13
          chmod +x gradlew
          cd ..

      - name: Build Signed APK + AAB (Clean)
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
