workflows:
  android-builds:
    name: Urban Auto - Final Signed Build
    max_build_duration: 120

    environment:
      node: 22
      java: 21
      groups:
        - supabase

    scripts:

      - name: Install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps

      - name: Build Next.js
        script: |
          npm run build

      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Generate Android icons
        script: |
          npx @capacitor/assets generate --android

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      # ---- FORCE FIX CORRUPT GRADLE WRAPPER ----
      - name: Regenerate Gradle wrapper (fix corrupt jar)
        script: |
          cd android
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.13
          chmod +x gradlew
          cd ..

      - name: Build Signed APK + AAB
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
